export const FB_ATTEMPTING = 'FB_ATTEMPTING';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const REFRESH_PROFILE = 'REFRESH_PROFILE';

export const ORGANIZE_ATTEMPTING = 'ORGANIZE_ATTEMPTING';
export const ORGANIZE_FAILED = 'ORGANIZE_FAILED';
export const ORGANIZE_SUCCESS = 'ORGANIZE_SUCCESS';

export const MEETINGS_FETCHED = 'MEETINGS_FETCHED';